"""enum skill category

Revision ID: 600e01112695
Revises: 6b2f32529635
Create Date: 2026-01-23 14:36:15.780840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600e01112695'
down_revision: Union[str, Sequence[str], None] = '6b2f32529635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    skill_category_enum = sa.Enum(
        'FRONTEND', 'BACKEND', 'INFRA', 'EXTERNAL', 'TOOLS', 'BAAS',
        name='skill_category_enum'
    )
    skill_category_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        """
        ALTER TABLE skills
        ALTER COLUMN category
        TYPE skill_category_enum
        USING category::skill_category_enum
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Downgrade schema."""
    # Enum → VARCHAR に戻す
    op.execute(
        """
        ALTER TABLE skills
        ALTER COLUMN category
        TYPE VARCHAR
        """
    )

    sa.Enum(
        'FRONTEND',
        'BACKEND',
        'INFRA',
        'EXTERNAL',
        'TOOLS',
        'BAAS',
        name='skill_category_enum'
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
